/*INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (1, 100, 'Vivaldi', 40, 1500, 10, 10, CURRENT_TIMESTAMP());*/

-- INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (1, 100, 'Vivaldi', 20.0, 1500, 10, 10, CURRENT_TIMESTAMP);
-- INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (2, 200, 'Steam', 60.0, 800, 200, 200, CURRENT_TIMESTAMP);
-- INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (3, 300, 'Google', 15.0, 500, 0, 0, CURRENT_TIMESTAMP);
-- INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (4, 400, 'Taskmanager', 8.0, 400, 100, 100, CURRENT_TIMESTAMP);
-- INSERT INTO PROCESS_RANK (ID, PID, `NAME`, CPU_USAGE, MEMORY_USAGE, DISK_READ_USAGE, DISK_WRITE_USAGE, LAST_UPDATE) VALUES (5, 500, 'Discord', 9.0, 200, 0, 0, CURRENT_TIMESTAMP);

